### ISSUE TITLE
Count number of frequency of Nucleotides in a DNA Sequence

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [CodeFlow201/DLib#42]
## Description
I want to add a function which will count the number of frequency of Nucleotides present in a DNA Sequence .

## Solution 
The function will take DNA sequence string as parameter . I will make a hash map (dictionary ) of different Nucleotides  , like A,T.C,G .which will keep track of number of frequency of Nucleotides . In the end , I will return the hash map , with the counted number of Nucleotides .

**Comment by rajinderpalsingh2001** [comment]
I think this function is already implemented, along with graph visualization.

**Comment by rajinderpalsingh2001** [comment]
https://www.github.com/CodeFlow201/DLib/tree/master/function_creation%2FcountAminoAcidsFromDna.ipynb

Here's the code for the same, if your issue is same as it, you close this one. :)

**Comment by vaibhavarora102** [comment]
@Rishabhraghwendra18  if it's not the same case, kindly reopen it

**Comment by Rishabhraghwendra18** [comment]
> https://www.github.com/CodeFlow201/DLib/tree/master/function_creation%2FcountAminoAcidsFromDna.ipynb
> 
> Here's the code for the same, if your issue is same as it, you close this one. :)

Ya it's same . Sorry I overlooked it
