### ISSUE TITLE
add contributor in readme

### ISSUE THREAD

**Issue by SanjeevKumar22** [CodeFlow201/DLib#44]

**Comment by Ayan-thecodeking** [comment]
i want to add contibuter section 
please asssign me this 
thank you :)

**Comment by Salonee-Jain** [comment]
Can I work on this issue?
I'm a LGM participant

**Comment by payaldutta** [comment]
If it's still up, I would like to work on this under LGMSOC'21.
Thank You.
@vaibhavarora102
