### ISSUE TITLE
Add Getting Started Section in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [CodeFlow201/DLib#45]
Add Getting Started Section in readme.md

**Comment by ishitakapoor26** [comment]
@vaibhavarora102 pls assign this issue to me under LGM-SOC'21

**Comment by ishitakapoor26** [comment]
@vaibhavarora102 pls review my pr and pls label this issue with level and lgm-soc'21.

**Comment by ishitakapoor26** [comment]
@vaibhavarora102 getting started section is not there. pls review my pr.

**Comment by vaibhavarora102** [comment]
hey! I think the necessary part is already explained in the readme itself and we no longer need all this stuff
