### ISSUE TITLE
Add Contribution Guidelines in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [CodeFlow201/DLib#46]
Add Contribution Guidelines in readme.md

**Comment by ishitakapoor26** [comment]
@vaibhavarora102 pls assign this issue to me under LGM-SOC'21

**Comment by ishitakapoor26** [comment]
@vaibhavarora102 pls review my pr.

**Comment by Ayan-thecodeking** [comment]
hey @vaibhavarora102 
i also want to work on this issue 
please asssign me for this

**Comment by ishitakapoor26** [comment]
> hey @vaibhavarora102
> i also want to work on this issue
> please asssign me for this

Hey i've already created a pr.You can look for another issue.
