### ISSUE TITLE
Print Double-Helix structure of DNA

### ISSUE THREAD

**Issue by akash-rajak** [CodeFlow201/DLib#53]
Want to add function to print the double-helix structure of DNA.

In this function we pass only one argument that is n, and function will print structure.

**Comment by akash-rajak** [comment]
@vaibhavarora102 , Please assign this to me under LGM SOC, want to add this function in function_creation directory.

**Comment by vaibhavarora102** [comment]
Assigned👍
Will shortly add required tags and labels

**Comment by akash-rajak** [comment]
Thanks @vaibhavarora102

**Comment by akash-rajak** [comment]
@vaibhavarora102 , If I complete with the coding part for this issue, should i wait for the labels to be added?

**Comment by vaibhavarora102** [comment]
Nopes , just go ahead and make pull request
I will apply labels before merging it

**Comment by akash-rajak** [comment]
ok

**Comment by akash-rajak** [comment]
@vaibhavarora102 , created the pr for adding function for printing double-helix structure of DNA, please check it
