### ISSUE TITLE
gc content using biopython library

### ISSUE THREAD

**Issue by akash-rajak** [CodeFlow201/DLib#57]
Want to add funtion to find the gc content in dna,
This function is already created without normal python coding
I want  to add a function which finds gc content using bio python library

**Comment by akash-rajak** [comment]
@vaibhavarora102 , if this issue is valid, please assign me under LGM SOC

**Comment by vaibhavarora102** [comment]
@akash435  we do not wish to use any such direct library
and moreover, this function is already in the functions folder

**Comment by akash-rajak** [comment]
ok
