### ISSUE TITLE
Logo for the DLIB WebApp

### ISSUE THREAD

**Issue by ghost** [CodeFlow201/DLib#61]
### Feature or Bug?
- [x] feature request.

### Describe the Feature?
I want to add a logo for this amazing WebApp project to make it more attractive

 ### Anything else ?
Please assign this to me and add labels to it. I want to contribute it under LGMSOC21

### Add the Snapshot
![LOGO](https://user-images.githubusercontent.com/71076194/122017431-94a25600-cddf-11eb-9d21-dd55021c01f7.gif)

**Comment by vaibhavarora102** [comment]
indeed a great logo, but actually team was discussing changing the name of the project, as the name seems a bit common.

I Will update you over this shortly

**Comment by ghost** [comment]
@vaibhavarora102 ok sure 👍

**Comment by ghost** [comment]
Hello @vaibhavarora102 Sir Have you decided about the name of the project ?

**Comment by vaibhavarora102** [comment]
We cant change the name till this program  ends, so, you can move to another issue

thanks for your efforts in designing the logo
