### ISSUE TITLE
add some badges to the README file

### ISSUE THREAD

**Issue by Umesh-01** [CodeFlow201/DLib#74]
## Description
add some badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

## Describe the solution you'd like

![image](https://user-images.githubusercontent.com/83420185/124011316-7fdbda00-d9fd-11eb-8e7e-abdd99171167.png)

I will add some badges at the top and also will add links related to them so that the README.md file will look more interactive and awesome.

### Work under/as

- [x] LGMSOC
- [ ] Contributor

**Comment by Umesh-01** [comment]
@vaibhavarora102 @sairish2001 Should I make these changes??

**Comment by rajinderpalsingh2001** [comment]
@Umesh-01 For what type of badges you want to add, Social Badges?

**Comment by Umesh-01** [comment]
Hello @sairish2001 

I will add some badges like this (see the image) and if you want me to add some social badges then definitely I can also add them. 
Just tell me the name of social media badges you want...

![image](https://user-images.githubusercontent.com/83420185/124110557-f91f0f80-da85-11eb-9f84-e928046c37b0.png)

**Comment by rajinderpalsingh2001** [comment]
@vaibhavarora102 have a look!

**Comment by vaibhavarora102** [comment]
Yeah! we can add this type of badges
